import { api, unwrap } from '@/lib/api';
export const CAMPAIGN_STATUS_LABELS = {
    DRAFT: 'Rascunho',
    SCHEDULED: 'Agendada',
    SENDING: 'Enviando',
    SENT: 'Enviada',
    PAUSED: 'Pausada',
    FAILED: 'Falhou',
};
export const marketingApi = {
    listCampaigns: async (status) => unwrap(await api.get('/marketing/campaigns', { params: { status } })),
    getCampaign: async (id) => unwrap(await api.get(`/marketing/campaigns/${id}`)),
    createCampaign: async (data) => unwrap(await api.post('/marketing/campaigns', data)),
    updateCampaign: async (id, data) => unwrap(await api.patch(`/marketing/campaigns/${id}`, data)),
    deleteCampaign: async (id) => await api.delete(`/marketing/campaigns/${id}`),
    scheduleCampaign: async (id, scheduledAt) => unwrap(await api.post(`/marketing/campaigns/${id}/schedule`, { scheduledAt })),
    sendCampaignNow: async (id) => unwrap(await api.post(`/marketing/campaigns/${id}/send-now`)),
    pauseCampaign: async (id) => unwrap(await api.post(`/marketing/campaigns/${id}/pause`)),
    listTemplates: async () => unwrap(await api.get('/marketing/templates')),
    createTemplate: async (data) => unwrap(await api.post('/marketing/templates', data)),
    updateTemplate: async (id, data) => unwrap(await api.patch(`/marketing/templates/${id}`, data)),
    duplicateTemplate: async (id) => unwrap(await api.post(`/marketing/templates/${id}/duplicate`)),
    deleteTemplate: async (id) => await api.delete(`/marketing/templates/${id}`),
    listAudiences: async () => unwrap(await api.get('/marketing/audiences')),
    createAudience: async (data) => unwrap(await api.post('/marketing/audiences', data)),
    updateAudience: async (id, data) => unwrap(await api.patch(`/marketing/audiences/${id}`, data)),
    deleteAudience: async (id) => await api.delete(`/marketing/audiences/${id}`),
    previewAudience: async (filters) => unwrap(await api.post('/marketing/audiences/preview', { filters })),
    listRecommendations: async () => unwrap(await api.get('/marketing/recommendations')),
    generateRecommendations: async () => unwrap(await api.post('/marketing/recommendations/generate')),
    acceptRecommendation: async (id) => unwrap(await api.post(`/marketing/recommendations/${id}/accept`)),
    dismissRecommendation: async (id) => unwrap(await api.post(`/marketing/recommendations/${id}/dismiss`)),
    getSettings: async () => unwrap(await api.get('/marketing/settings')),
    updateSettings: async (data) => unwrap(await api.patch('/marketing/settings', data)),
};
