import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ChevronRight } from 'lucide-react';
import { Drawer } from '@/components/ui/Drawer';
import { webhooksApi } from '@/api/webhooks.api';
export function DeliveriesDrawer({ webhookId, open, onClose }) {
    const [expanded, setExpanded] = useState(null);
    const [page, setPage] = useState(1);
    const { data, isLoading } = useQuery({
        queryKey: ['webhook-deliveries', webhookId, page],
        queryFn: () => webhooksApi.deliveries(webhookId, page, 25),
        enabled: open && !!webhookId,
    });
    return (_jsx(Drawer, { open: open, onClose: onClose, width: "lg", title: "Hist\u00F3rico de entregas", children: _jsxs("div", { className: "p-5", children: [isLoading && _jsx("p", { className: "text-sm text-muted-foreground", children: "Carregando..." }), data?.items.length === 0 && (_jsx("p", { className: "text-sm text-muted-foreground", children: "Nenhuma entrega registrada ainda." })), _jsx("div", { className: "space-y-2", children: data?.items.map((d) => (_jsx(DeliveryRow, { delivery: d, expanded: expanded === d.id, onToggle: () => setExpanded(expanded === d.id ? null : d.id) }, d.id))) }), data && data.pages > 1 && (_jsxs("div", { className: "mt-3 flex items-center justify-between", children: [_jsxs("span", { className: "text-xs text-muted-foreground", children: ["P\u00E1gina ", data.page, " de ", data.pages] }), _jsxs("div", { className: "flex gap-1", children: [_jsx("button", { type: "button", disabled: page <= 1, onClick: () => setPage((p) => p - 1), className: "h-7 rounded-md border border-border bg-card px-3 text-xs disabled:opacity-40", children: "Anterior" }), _jsx("button", { type: "button", disabled: page >= data.pages, onClick: () => setPage((p) => p + 1), className: "h-7 rounded-md border border-border bg-card px-3 text-xs disabled:opacity-40", children: "Pr\u00F3xima" })] })] }))] }) }));
}
function DeliveryRow({ delivery, expanded, onToggle, }) {
    return (_jsxs("div", { className: "rounded-md border border-border bg-card", children: [_jsxs("button", { type: "button", onClick: onToggle, className: "flex w-full items-center gap-2 p-2 text-left hover:bg-muted/40", children: [_jsx(ChevronRight, { className: `h-4 w-4 text-muted-foreground transition-transform ${expanded ? 'rotate-90' : ''}` }), _jsxs("div", { className: "flex-1", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("code", { className: "text-xs font-semibold text-foreground", children: delivery.event }), _jsx("span", { className: `rounded-md px-1.5 py-0.5 text-[10px] font-bold ${delivery.success ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`, children: delivery.statusCode ?? 'ERR' }), delivery.latencyMs !== null && (_jsxs("span", { className: "text-[11px] text-muted-foreground", children: [delivery.latencyMs, "ms"] })), _jsxs("span", { className: "text-[11px] text-muted-foreground", children: ["tentativa ", delivery.attempt] })] }), _jsx("span", { className: "text-[11px] text-muted-foreground", children: new Date(delivery.createdAt).toLocaleString('pt-BR') })] })] }), expanded && (_jsxs("div", { className: "space-y-2 border-t border-border p-3", children: [_jsxs("div", { children: [_jsx("span", { className: "field-label", children: "Payload enviado" }), _jsx("pre", { className: "max-h-32 overflow-auto rounded-md bg-foreground/10 dark:bg-foreground/5 p-2 text-[11px] text-foreground", children: JSON.stringify(delivery.payload, null, 2) })] }), _jsxs("div", { children: [_jsx("span", { className: "field-label", children: "Response body" }), _jsx("pre", { className: "max-h-32 overflow-auto rounded-md bg-muted/40 p-2 text-[11px] text-foreground/80", children: delivery.responseBody ?? '(vazio)' })] })] }))] }));
}
